package com.example.shyam_assignment.data.local.dao

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import com.example.shyam_assignment.data.local.entity.SummaryEntity
import kotlinx.coroutines.flow.Flow

/**
 * DAO for meeting summaries.
 * One summary per session — generated by Gemini AI.
 */
@Dao
interface SummaryDao {

    /** Insert a new summary or update an existing one */
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertOrUpdate(summary: SummaryEntity)

    /** Get a session's summary (live updates via Flow) */
    @Query("SELECT * FROM summaries WHERE sessionId = :sessionId")
    fun getSummaryBySessionFlow(sessionId: String): Flow<SummaryEntity?>

    /** Get a session's summary (one-time read) */
    @Query("SELECT * FROM summaries WHERE sessionId = :sessionId")
    suspend fun getSummaryBySession(sessionId: String): SummaryEntity?

    /** Delete a session's summary */
    @Query("DELETE FROM summaries WHERE sessionId = :sessionId")
    suspend fun deleteSummary(sessionId: String)

    /** Get summaries that are still pending/generating — used for recovery */
    @Query("SELECT * FROM summaries WHERE status IN (:statuses)")
    suspend fun getSummariesByStatuses(statuses: List<String>): List<SummaryEntity>
}
