package com.example.shyam_assignment.data.local.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Room entity for a recording session.
 * Each time the user presses Record, one session is created.
 * Stores metadata like start/end time, duration, and current status.
 */
@Entity(tableName = "recording_sessions")
data class RecordingSessionEntity(
    @PrimaryKey
    val sessionId: String,                              // Unique ID for this session
    val title: String? = null,                          // Title (set by Gemini summary later)
    val startedAt: Long,                                // When recording started (epoch ms)
    val endedAt: Long? = null,                          // When recording stopped (epoch ms)
    val durationMs: Long = 0L,                          // Total recording duration in ms
    val status: String = SessionStatus.IDLE,             // Current lifecycle status
    val warningMessage: String? = null,                  // Any warning shown during recording
    val errorMessage: String? = null,                    // Error message if something failed
    val activeInputSource: String? = null,               // Mic source (MICROPHONE, BLUETOOTH, etc.)
    val createdAt: Long = System.currentTimeMillis(),    // Row creation timestamp
    val updatedAt: Long = System.currentTimeMillis()     // Last update timestamp
)

/**
 * All possible statuses a recording session can be in.
 * Moves through: IDLE → RECORDING → STOPPED → COMPLETED
 */
object SessionStatus {
    const val IDLE = "IDLE"                 // Not started yet
    const val RECORDING = "RECORDING"       // Actively capturing audio
    const val PAUSED = "PAUSED"             // Paused (phone call, audio focus lost)
    const val STOPPED = "STOPPED"           // Recording finished, waiting for transcription/summary
    const val TRANSCRIBING = "TRANSCRIBING" // Chunks are being transcribed by Gemini
    const val SUMMARIZING = "SUMMARIZING"   // Summary is being generated by Gemini
    const val COMPLETED = "COMPLETED"       // Transcript + summary both done
    const val ERROR = "ERROR"               // Something failed
}
