package com.example.shyam_assignment.data.local.entity

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.PrimaryKey

/**
 * Room entity for the AI-generated summary of a session.
 * One summary per session. Contains title, summary text,
 * action items, and key points — all generated by Gemini.
 */
@Entity(
    tableName = "summaries",
    foreignKeys = [
        ForeignKey(
            entity = RecordingSessionEntity::class,
            parentColumns = ["sessionId"],
            childColumns = ["sessionId"],
            onDelete = ForeignKey.CASCADE
        )
    ]
)
data class SummaryEntity(
    @PrimaryKey
    val sessionId: String,                          // Links to the recording session
    val title: String = "",                         // AI-generated meeting title
    val summary: String = "",                       // AI-generated summary paragraph
    val actionItemsJson: String = "[]",             // JSON array of action item strings
    val keyPointsJson: String = "[]",               // JSON array of key point strings
    val status: String = SummaryStatus.PENDING,     // Current generation status
    val errorMessage: String? = null,               // Error message if generation failed
    val partialContent: String? = null,             // Partial content (if generation interrupted)
    val updatedAt: Long = System.currentTimeMillis()
)

/**
 * Possible states for summary generation.
 */
object SummaryStatus {
    const val PENDING = "PENDING"       // Not yet started
    const val GENERATING = "GENERATING" // Gemini is working on it
    const val COMPLETED = "COMPLETED"   // Summary is ready
    const val FAILED = "FAILED"         // Generation failed
}

